spring:
  application:
    name: labboot-ajax

  profiles:
    active: '@xxxx@'

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=java;trustServerCertificate=true
    username: sa
    password: P@ssw0rd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    database-platform: org.hibernate.dialect.SQLServerDialect
  output:
    ansi:
      enabled: always
jwt:
    token:
      expire: 10
